<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use App\Models\User;
use App\Models\Doctor;
use App\Models\Specialty;

class DoctorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Clear existing doctors and users to avoid conflicts
        \DB::table('doctors')->delete();
        \DB::table('users')->where('user_type', 'doctor')->delete();

        // Get specialties
        $specialties = Specialty::all();

        // Create test doctors
        $doctors = [
            [
                'first_name' => 'Dr. Ahmed',
                'last_name' => 'Ben Ali',
                'email' => 'ahmed.benali@rdvmedical.tn',
                'phone' => '+216 71 234 567',
                'birth_date' => '1980-05-15',
                'address' => '123 Rue de la Santé, Tunis',
                'user_type' => 'doctor',
                'password' => Hash::make('password123'),
                'specialty_id' => 2, // Cardiologie
                'experience_years' => 15,
                'consultation_fee' => 80.00,
                'available_days' => ['lundi', 'mardi', 'mercredi', 'jeudi'],
                'start_time' => '09:00',
                'end_time' => '17:00',
                'description' => 'Cardiologue expérimenté spécialisé dans les maladies cardiovasculaires.',
                'education' => 'Faculté de Médecine de Tunis, Spécialisation en Cardiologie',
                'certifications' => 'Certification en Échocardiographie, Diplôme de Cardiologie Interventionnelle',
                'languages' => ['arabe', 'français', 'anglais'],
                'image' => 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&h=400&fit=crop&crop=face',
            ],
            [
                'first_name' => 'Dr. Fatma',
                'last_name' => 'Zghal',
                'email' => 'fatma.zghal@rdvmedical.tn',
                'phone' => '+216 71 345 678',
                'birth_date' => '1985-08-22',
                'address' => '456 Avenue Habib Bourguiba, Sfax',
                'user_type' => 'doctor',
                'password' => Hash::make('password123'),
                'specialty_id' => 3, // Dermatologie
                'experience_years' => 12,
                'consultation_fee' => 70.00,
                'available_days' => ['lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi'],
                'start_time' => '08:00',
                'end_time' => '16:00',
                'description' => 'Dermatologue spécialisée dans le traitement des maladies de la peau.',
                'education' => 'Faculté de Médecine de Sfax, Spécialisation en Dermatologie',
                'certifications' => 'Certification en Dermatologie Esthétique, Diplôme de Dermatologie Chirurgicale',
                'languages' => ['arabe', 'français'],
                'image' => 'https://images.unsplash.com/photo-1594824475545-9d0e4b6b8b8b?w=400&h=400&fit=crop&crop=face',
            ],
            [
                'first_name' => 'Dr. Mohamed',
                'last_name' => 'Trabelsi',
                'email' => 'mohamed.trabelsi@rdvmedical.tn',
                'phone' => '+216 71 456 789',
                'birth_date' => '1978-12-10',
                'address' => '789 Rue de la Paix, Sousse',
                'user_type' => 'doctor',
                'password' => Hash::make('password123'),
                'specialty_id' => 6, // Pédiatrie
                'experience_years' => 20,
                'consultation_fee' => 60.00,
                'available_days' => ['lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi'],
                'start_time' => '08:30',
                'end_time' => '18:00',
                'description' => 'Pédiatre expérimenté spécialisé dans les soins aux enfants.',
                'education' => 'Faculté de Médecine de Sousse, Spécialisation en Pédiatrie',
                'certifications' => 'Certification en Néonatologie, Diplôme de Pédiatrie Générale',
                'languages' => ['arabe', 'français', 'anglais'],
                'image' => 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400&h=400&fit=crop&crop=face',
            ],
            [
                'first_name' => 'Dr. Salma',
                'last_name' => 'Hammami',
                'email' => 'salma.hammami@rdvmedical.tn',
                'phone' => '+216 71 567 890',
                'birth_date' => '1982-03-18',
                'address' => '321 Boulevard de la Liberté, Monastir',
                'user_type' => 'doctor',
                'password' => Hash::make('password123'),
                'specialty_id' => 7, // Gynécologie
                'experience_years' => 14,
                'consultation_fee' => 85.00,
                'available_days' => ['lundi', 'mardi', 'mercredi', 'jeudi'],
                'start_time' => '09:00',
                'end_time' => '16:30',
                'description' => 'Gynécologue spécialisée dans la santé des femmes.',
                'education' => 'Faculté de Médecine de Monastir, Spécialisation en Gynécologie',
                'certifications' => 'Certification en Échographie Gynécologique, Diplôme de Gynécologie Obstétrique',
                'languages' => ['arabe', 'français'],
                'image' => 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&h=400&fit=crop&crop=face',
            ],
            [
                'first_name' => 'Dr. Karim',
                'last_name' => 'Bouaziz',
                'email' => 'karim.bouaziz@rdvmedical.tn',
                'phone' => '+216 71 678 901',
                'birth_date' => '1987-07-25',
                'address' => '654 Rue des Oliviers, Gabès',
                'user_type' => 'doctor',
                'password' => Hash::make('password123'),
                'specialty_id' => 4, // Orthopédie
                'experience_years' => 10,
                'consultation_fee' => 90.00,
                'available_days' => ['lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi'],
                'start_time' => '08:00',
                'end_time' => '17:00',
                'description' => 'Orthopédiste spécialisé dans les problèmes musculo-squelettiques.',
                'education' => 'Faculté de Médecine de Gabès, Spécialisation en Orthopédie',
                'certifications' => 'Certification en Chirurgie Orthopédique, Diplôme de Traumatologie',
                'languages' => ['arabe', 'français', 'anglais'],
                'image' => 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400&h=400&fit=crop&crop=face',
            ],
            [
                'first_name' => 'Dr. Leila',
                'last_name' => 'Mansouri',
                'email' => 'leila.mansouri@rdvmedical.tn',
                'phone' => '+216 72 123 456',
                'birth_date' => '1983-11-12',
                'address' => '987 Boulevard de la République, Tunis',
                'user_type' => 'doctor',
                'password' => Hash::make('password123'),
                'specialty_id' => 5, // Neurologie
                'experience_years' => 16,
                'consultation_fee' => 95.00,
                'available_days' => ['lundi', 'mardi', 'mercredi', 'jeudi'],
                'start_time' => '09:30',
                'end_time' => '17:30',
                'description' => 'Neurologue spécialisée dans les troubles neurologiques et les maladies du cerveau.',
                'education' => 'Faculté de Médecine de Tunis, Spécialisation en Neurologie',
                'certifications' => 'Certification en Électroencéphalographie, Diplôme de Neurologie Clinique',
                'languages' => ['arabe', 'français', 'anglais'],
                'image' => 'https://images.unsplash.com/photo-1594824475545-9d0e4b6b8b8b?w=400&h=400&fit=crop&crop=face',
            ],
            [
                'first_name' => 'Dr. Hassen',
                'last_name' => 'Kacem',
                'email' => 'hassen.kacem@rdvmedical.tn',
                'phone' => '+216 73 234 567',
                'birth_date' => '1975-09-08',
                'address' => '147 Rue de la Kasbah, Kairouan',
                'user_type' => 'doctor',
                'password' => Hash::make('password123'),
                'specialty_id' => 8, // Psychiatrie
                'experience_years' => 22,
                'consultation_fee' => 75.00,
                'available_days' => ['lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi'],
                'start_time' => '08:30',
                'end_time' => '16:30',
                'description' => 'Psychiatre expérimenté spécialisé dans les troubles mentaux et le bien-être psychologique.',
                'education' => 'Faculté de Médecine de Tunis, Spécialisation en Psychiatrie',
                'certifications' => 'Certification en Thérapie Cognitivo-Comportementale, Diplôme de Psychiatrie',
                'languages' => ['arabe', 'français'],
                'image' => 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&h=400&fit=crop&crop=face',
            ],
            [
                'first_name' => 'Dr. Nadia',
                'last_name' => 'Belhaj',
                'email' => 'nadia.belhaj@rdvmedical.tn',
                'phone' => '+216 74 345 678',
                'birth_date' => '1988-04-20',
                'address' => '258 Avenue de la Victoire, Bizerte',
                'user_type' => 'doctor',
                'password' => Hash::make('password123'),
                'specialty_id' => 9, // Dentisterie
                'experience_years' => 9,
                'consultation_fee' => 65.00,
                'available_days' => ['lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi'],
                'start_time' => '09:00',
                'end_time' => '18:00',
                'description' => 'Dentiste spécialisée dans les soins dentaires préventifs et curatifs.',
                'education' => 'Faculté de Médecine Dentaire de Tunis, Diplôme en Chirurgie Dentaire',
                'certifications' => 'Certification en Implantologie, Diplôme de Parodontologie',
                'languages' => ['arabe', 'français', 'anglais'],
                'image' => 'https://images.unsplash.com/photo-1594824475545-9d0e4b6b8b8b?w=400&h=400&fit=crop&crop=face',
            ],
            [
                'first_name' => 'Dr. Sami',
                'last_name' => 'Gharbi',
                'email' => 'sami.gharbi@rdvmedical.tn',
                'phone' => '+216 75 456 789',
                'birth_date' => '1981-06-14',
                'address' => '369 Rue de l\'Indépendance, Nabeul',
                'user_type' => 'doctor',
                'password' => Hash::make('password123'),
                'specialty_id' => 10, // Ophtalmologie
                'experience_years' => 13,
                'consultation_fee' => 85.00,
                'available_days' => ['lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi'],
                'start_time' => '08:00',
                'end_time' => '16:00',
                'description' => 'Ophtalmologue spécialisé dans les maladies des yeux et la chirurgie oculaire.',
                'education' => 'Faculté de Médecine de Tunis, Spécialisation en Ophtalmologie',
                'certifications' => 'Certification en Chirurgie Rétinienne, Diplôme d\'Ophtalmologie',
                'languages' => ['arabe', 'français', 'anglais'],
                'image' => 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400&h=400&fit=crop&crop=face',
            ],
            [
                'first_name' => 'Dr. Amina',
                'last_name' => 'Saidi',
                'email' => 'amina.saidi@rdvmedical.tn',
                'phone' => '+216 76 567 890',
                'birth_date' => '1984-02-28',
                'address' => '741 Boulevard de l\'Environnement, Hammamet',
                'user_type' => 'doctor',
                'password' => Hash::make('password123'),
                'specialty_id' => 11, // Gastro-entérologie
                'experience_years' => 11,
                'consultation_fee' => 80.00,
                'available_days' => ['lundi', 'mardi', 'mercredi', 'jeudi'],
                'start_time' => '09:00',
                'end_time' => '17:00',
                'description' => 'Gastro-entérologue spécialisée dans les maladies digestives et hépatiques.',
                'education' => 'Faculté de Médecine de Sousse, Spécialisation en Gastro-entérologie',
                'certifications' => 'Certification en Endoscopie Digestive, Diplôme d\'Hépatologie',
                'languages' => ['arabe', 'français'],
                'image' => 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&h=400&fit=crop&crop=face',
            ],
            [
                'first_name' => 'Dr. Youssef',
                'last_name' => 'Mejri',
                'email' => 'youssef.mejri@rdvmedical.tn',
                'phone' => '+216 77 678 901',
                'birth_date' => '1979-12-05',
                'address' => '852 Rue de la Médina, Tozeur',
                'user_type' => 'doctor',
                'password' => Hash::make('password123'),
                'specialty_id' => 2, // Cardiologie (additional cardiologist)
                'experience_years' => 18,
                'consultation_fee' => 100.00,
                'available_days' => ['lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi'],
                'start_time' => '08:30',
                'end_time' => '16:30',
                'description' => 'Cardiologue spécialisé dans l\'électrophysiologie et les arythmies cardiaques.',
                'education' => 'Faculté de Médecine de Tunis, Spécialisation en Cardiologie',
                'certifications' => 'Certification en Électrophysiologie Cardiaque, Diplôme de Rythmologie',
                'languages' => ['arabe', 'français', 'anglais'],
                'image' => 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400&h=400&fit=crop&crop=face',
            ],
            [
                'first_name' => 'Dr. Ines',
                'last_name' => 'Cherif',
                'email' => 'ines.cherif@rdvmedical.tn',
                'phone' => '+216 78 789 012',
                'birth_date' => '1986-08-17',
                'address' => '963 Avenue des Roses, Mahdia',
                'user_type' => 'doctor',
                'password' => Hash::make('password123'),
                'specialty_id' => 3, // Dermatologie (additional dermatologist)
                'experience_years' => 8,
                'consultation_fee' => 75.00,
                'available_days' => ['mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi'],
                'start_time' => '10:00',
                'end_time' => '18:00',
                'description' => 'Dermatologue spécialisée dans la dermatologie esthétique et anti-âge.',
                'education' => 'Faculté de Médecine de Monastir, Spécialisation en Dermatologie',
                'certifications' => 'Certification en Médecine Esthétique, Diplôme de Dermatologie Cosmétique',
                'languages' => ['arabe', 'français', 'anglais'],
                'image' => 'https://images.unsplash.com/photo-1594824475545-9d0e4b6b8b8b?w=400&h=400&fit=crop&crop=face',
            ],
            [
                'first_name' => 'Dr. Bilel',
                'last_name' => 'Jlassi',
                'email' => 'bilel.jlassi@rdvmedical.tn',
                'phone' => '+216 79 890 123',
                'birth_date' => '1990-01-30',
                'address' => '159 Boulevard de la Mer, Sidi Bou Said',
                'user_type' => 'doctor',
                'password' => Hash::make('password123'),
                'specialty_id' => 6, // Pédiatrie (additional pediatrician)
                'experience_years' => 6,
                'consultation_fee' => 55.00,
                'available_days' => ['lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi'],
                'start_time' => '09:00',
                'end_time' => '17:00',
                'description' => 'Pédiatre spécialisé dans la médecine préventive infantile et les vaccinations.',
                'education' => 'Faculté de Médecine de Tunis, Spécialisation en Pédiatrie',
                'certifications' => 'Certification en Vaccinologie, Diplôme de Pédiatrie Préventive',
                'languages' => ['arabe', 'français', 'anglais'],
                'image' => 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&h=400&fit=crop&crop=face',
            ],
            [
                'first_name' => 'Dr. Rania',
                'last_name' => 'Ben Amor',
                'email' => 'rania.benamor@rdvmedical.tn',
                'phone' => '+216 20 123 456',
                'birth_date' => '1989-05-22',
                'address' => '357 Rue de Carthage, Carthage',
                'user_type' => 'doctor',
                'password' => Hash::make('password123'),
                'specialty_id' => 7, // Gynécologie (additional gynecologist)
                'experience_years' => 7,
                'consultation_fee' => 70.00,
                'available_days' => ['lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi'],
                'start_time' => '08:00',
                'end_time' => '15:00',
                'description' => 'Gynécologue spécialisée dans la santé reproductive et la contraception.',
                'education' => 'Faculté de Médecine de Tunis, Spécialisation en Gynécologie',
                'certifications' => 'Certification en Planification Familiale, Diplôme de Gynécologie Médicale',
                'languages' => ['arabe', 'français'],
                'image' => 'https://images.unsplash.com/photo-1594824475545-9d0e4b6b8b8b?w=400&h=400&fit=crop&crop=face',
            ],
        ];

        foreach ($doctors as $doctorData) {
            // Create user
            $user = User::create([
                'first_name' => $doctorData['first_name'],
                'last_name' => $doctorData['last_name'],
                'email' => $doctorData['email'],
                'phone' => $doctorData['phone'],
                'birth_date' => $doctorData['birth_date'],
                'address' => $doctorData['address'],
                'user_type' => $doctorData['user_type'],
                'password' => $doctorData['password'],
            ]);

            // Create doctor profile
            Doctor::create([
                'user_id' => $user->id,
                'specialty_id' => $doctorData['specialty_id'],
                'experience_years' => $doctorData['experience_years'],
                'consultation_fee' => $doctorData['consultation_fee'],
                'available_days' => $doctorData['available_days'],
                'start_time' => $doctorData['start_time'],
                'end_time' => $doctorData['end_time'],
                'description' => $doctorData['description'],
                'education' => $doctorData['education'],
                'certifications' => $doctorData['certifications'],
                'languages' => $doctorData['languages'],
                'image' => $doctorData['image'],
            ]);
        }
    }
}
