services:
  - type: web
    name: laravel-app
    runtime: php
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: php artisan serve --host=0.0.0.0 --port=10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: ton-host
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: medical_rdv
      - key: DB_USERNAME
        value: ton-utilisateur
      - key: DB_PASSWORD
        value: ton-mdp
